name: Build & Deploy Jekyll Site (official)

permissions:
  contents: read      # 체크아웃용
  pages: write        # Pages API 호출 권한
  id-token: write     # OIDC 인증

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          cache: bundler

      - name: Install Bundler
        run: gem install bundler -v 2.4.22

      - name: Bundle install
        run: bundle _2.4.22_ install --jobs 4 --retry 3

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        # secrets.GITHUB_TOKEN 자동 사용
