name: CI / Build & Deploy Jekyll Site

on:
  push:
    branches:
      - main   # 혹은 여러분의 기본 브랜치 이름

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Ruby 환경 세팅
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1        # 여러분의 Gemfile에 맞는 버전
          cache: bundler           # Bundler 캐시 활성화

      # 3. Bundler 설치 (필요한 경우)
      - name: Install Bundler
        run: gem install bundler

      # 4. Gem 의존성 설치
      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      # 5. Jekyll 사이트 빌드
      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site

      # 6. 빌드 결과물을 gh-pages 브랜치에 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # publish_branch: gh-pages    # 기본값이 gh-pages, 필요시 변경
          # user_name: your-bot-name     # 커밋 유저 설정 (옵션)
          # user_email: your-bot-email

