name: Build & Deploy Personal Site

# GitHub Pages 권한 설정
permissions:
  contents: write   # main 브랜치 푸시 권한
  pages: write      # GitHub Pages 배포 권한
  id-token: write   # Actions deploy 권한

on:
  push:
    branches:
      - main       # 변경 감지할 브랜치

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    1. Checkout  
      uses: actions/checkout@v3

    2. Ruby + Bundler 설정  
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        cache: bundler  

    3. Bundler 설치  
      run: gem install bundler -v 2.4.22

    4. Gem 설치  
      run: bundle _2.4.22_ install --jobs 4 --retry 3

    5. Jekyll 빌드  
      run: bundle exec jekyll build --destination _site

    6. 페이지 배포  
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: main   # main 브랜치 루트에 배포
